name: Java Deploy to server

on:
  push:
    branches:
      - main

env:
  application_properties: ${{ secrets.APP_PROPERTIES }}
  jarFileName: admin-0.0.1-SNAPSHOT.jar
  folder_project: sc-admin
  PORT: 8090

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Config application.yml
        run: |
          echo "${{ env.application_properties }}" > ./src/main/resources/application.yml

      - name: Maven Install and Package
        run: |
          ./mvnw install --file pom.xml
          echo "Comprimiendo archivos..."
          tar -czf ${{ github.sha }}.tgz target/${{ env.jarFileName }}

      - name: Load to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ github.sha }}.tgz
          target: ~/backend/${{ env.folder_project }}

      - name: Deploy on Server
        env:
          COMMAND_DEPLOY: java -jar ~/backend/${{ env.folder_project }}/${{ env.jarFileName }} > ~/backend/${{ env.folder_project }}/log.txt &
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/backend/${{ env.folder_project }}
            echo "Deteniendo proceso..."
            kill -9 $(lsof -t -i:${{ env.PORT }}) || true
            sleep 5
            echo "Descomprimiendo archivos..."
            tar -xzf ${{ github.sha }}.tgz --strip-components=1
            rm ${{ github.sha }}.tgz
            echo "Iniciando proceso..."
            java -jar ~/backend/${{ env.folder_project }}/${{ env.jarFileName }} > ~/backend/${{ env.folder_project }}/log.txt &
